### ISSUE TITLE
How can I see the details from the original image under the mask + increase edge detection accuracy

### ISSUE THREAD

**Issue by piovis2023** [spacepxl/ComfyUI-Florence-2#13]
Great node - thanks!

How can I see the details from the original image under the mask + increase edge detection accuracy?

For example, in the following workflow, I can see the mask detected but not what is under it. I'd like to see only the original image captured under the mask.

Also is there a way to increase the edge detection accuracy/closeness?

<img width="277" alt="image" src="https://github.com/spacepxl/ComfyUI-Florence-2/assets/130514657/b251f507-f794-4f1f-b964-52cc0cf60862">

Thank you

**Comment by spacepxl** [comment]
The preview output is just for preview. If you want to use the mask you need a postprocess node as in the examples, and then you can just invert the mask after.

Edge accuracy is just down to the Florence model, there's nothing that can be adjusted there. I would recommend using [Segment Anything](https://github.com/storyicon/comfyui_segment_anything) for actual segmentation/masking tasks.
