### ISSUE TITLE
Keeps redownloading the model after each restart

### ISSUE THREAD

**Issue by Davikar** [spacepxl/ComfyUI-Florence-2#14]
The model loader is redownloading the Florence 2 model from Huggingface every time I have restarted Comfy...
(Latest version of Comfy all extensions updated.)

**Comment by spacepxl** [comment]
I'm unable to reproduce this, it does redownload if the model is not in the new location in models/LLM, but only once, then it loads from cache correctly. By any chance do you have kijai's florence2 nodes installed also? He's using a slightly different method to download the models and I'm wondering if it conflicts.

**Comment by Davikar** [comment]
Well I'm not having this issue anymore. I think the better model management patch might have fixed it. I probably didn't have that when I opened this issue.
